[TASK-26] add mappers and tests to mic-hex-escs clean transformers
sokimaaa/ecommerce-platform pull request #29
Opened 2024-02-23 15:03 UTC by kateryna-mykh

2024-02-23 20:21 UTC, sokimaaa requested changes

2024-02-23 20:21 UTC, sokimaaa commented on saas/mic-hex-escs/domain/src/main/java/com/sokima/saas/mic/hex/escs/domain/transformer/clean/Tuple2CleanedCartTransformer.java
> +
redundant empty line 
```suggestion
```

2024-02-23 20:21 UTC, sokimaaa commented on saas/mic-hex-escs/domain/src/main/java/com/sokima/saas/mic/hex/escs/domain/transformer/clean/Tuple2CleanerResponseTransformer.java
> +
redundant empty line 
```suggestion
```

2024-02-23 20:21 UTC, sokimaaa commented on saas/mic-hex-escs/domain/src/main/java/com/sokima/saas/mic/hex/escs/domain/transformer/clean/mapper/Tuple2CleanedCartMapper.java
> +    @Mapping(target = "userId", expression = "java(input.getT2().cartId())")
1. why `userId` maps to`cartId` ? it may be different

2. such mapping could be simplified
```suggestion
    @Mapping(target = "userId", source= "t2.cartId")
```

2024-02-23 20:21 UTC, sokimaaa commented on saas/mic-hex-escs/domain/src/main/java/com/sokima/saas/mic/hex/escs/domain/transformer/clean/mapper/Tuple2CleanedCartMapper.java
> +    }
rewrite using guava multiset
```suggestion
```

2024-02-23 20:21 UTC, sokimaaa commented on saas/mic-hex-escs/domain/src/main/java/com/sokima/saas/mic/hex/escs/domain/transformer/clean/mapper/Tuple2CleanerResponseMapper.java
> +        final Cart transformed = new Tuple2CleanedCartTransformer().transform(input);
method creates new transformer every time is being invoked.

2024-02-23 20:21 UTC, sokimaaa commented on saas/mic-hex-escs/domain/src/main/java/com/sokima/saas/mic/hex/escs/domain/transformer/clean/mapper/Tuple2CleanerResponseMapper.java
> +        final Cart transformed = new Tuple2CleanedCartTransformer().transform(input);
SRP violation
1. Creating transformer
2. Doing logic

2024-02-23 20:21 UTC, sokimaaa commented on saas/mic-hex-escs/domain/src/test/java/com/sokima/saas/mic/hex/escs/domain/transformer/clean/Tuple2CleanedCartTransformerTest.java
> +        EqualsBuilder.reflectionEquals(expected, actual);
reflection is time consuming. 

we are strive to have test execution time as fast as possible. 
it's improve CI/CD.

So, just use assertEquals separately for each field
```suggestion
Assertions.assertEquals("expected", actual.actual(), "Blablabla");
```

2024-02-23 20:21 UTC, sokimaaa commented on saas/mic-hex-escs/domain/src/test/java/com/sokima/saas/mic/hex/escs/domain/transformer/clean/Tuple2CleanerResponseTransformerTest.java
> +    void transform_mappingValid_True() {
missing case for unhappy path. 

e.g. 
original [1, 2, 3, 3, 3]

payload = [1, 2, 3, 3]
happyUpdate = [3]
wrongUpdate = [3, 3]
wrongUpdate2 = [1, 2, 3, 3, 3]

2024-02-23 20:21 UTC, sokimaaa commented on saas/mic-hex-escs/domain/src/test/java/com/sokima/saas/mic/hex/escs/domain/transformer/clean/Tuple2CleanedCartTransformerTest.java
> +        final Long cartId = 123L;
use `var` when the type is obvious, e.g. when use `new`, instantiate primitive, and et cetera.

2024-02-23 21:01 UTC, kateryna-mykh commented on saas/mic-hex-escs/domain/src/main/java/com/sokima/saas/mic/hex/escs/domain/transformer/clean/mapper/Tuple2CleanedCartMapper.java
> +    @Mapping(target = "userId", expression = "java(input.getT2().cartId())")
Changed to cartId, but couldn't be simplified, because "Cart has no properties"

2024-02-23 21:04 UTC, kateryna-mykh commented on saas/mic-hex-escs/domain/src/main/java/com/sokima/saas/mic/hex/escs/domain/transformer/clean/mapper/Tuple2CleanerResponseMapper.java
> +        final Cart transformed = new Tuple2CleanedCartTransformer().transform(input);
Method was deleted, was set hardcode value till the logic structure changes

2024-02-24 12:33 UTC, kateryna-mykh commented on saas/mic-hex-escs/domain/src/main/java/com/sokima/saas/mic/hex/escs/domain/transformer/clean/mapper/Tuple2CleanedCartMapper.java
> +    }
fixed

2024-02-25 09:17 UTC, sokimaaa approved these changes

2024-02-25 09:17 UTC, sokimaaa commented on saas/mic-hex-escs/domain/src/main/java/com/sokima/saas/mic/hex/escs/domain/transformer/clean/mapper/Tuple2CleanedCartMapper.java
> +    @Mapping(target = "userId", expression = "java(input.getT2().userId())")
use java expression only when any supported features are not working. 
here you can use source = "t2.userId" like you did it for previous mapping. 
```suggestion
    @Mapping(target = "userId", source= "t2.userId")
```

2024-02-25 09:17 UTC, merged